### ISSUE TITLE
Unable to download vaccination data for nations

### ISSUE THREAD

**Issue by przemyslawpluta** [publichealthengland/coronavirus-dashboard-layouts#59]
**Describe the bug**
Can not export data or query from dashboard for Vaccinations.

**To Reproduce**
Go to https://coronavirus.data.gov.uk/details/vaccinations?areaType=nation&areaName=England and and select any option Daily, Cumulative or Data then try to download any flavour e.g. CSV, JSON or XML. Redirect query: https://coronavirus.data.gov.uk/api/v1/data?filters=&structure={"areaType":"areaType","areaName":"areaName","areaCode":"areaCode","date":"date","newPeopleVaccinatedFirstDoseByPublishDate":"newPeopleVaccinatedFirstDoseByPublishDate","cumPeopleVaccinatedFirstDoseByPublishDate":"cumPeopleVaccinatedFirstDoseByPublishDate","newPeopleVaccinatedSecondDoseByPublishDate":"newPeopleVaccinatedSecondDoseByPublishDate","cumPeopleVaccinatedSecondDoseByPublishDate":"cumPeopleVaccinatedSecondDoseByPublishDate","newPeopleVaccinatedThirdInjectionByPublishDate":"newPeopleVaccinatedThirdInjectionByPublishDate","cumPeopleVaccinatedThirdInjectionByPublishDate":"cumPeopleVaccinatedThirdInjectionByPublishDate"}&format=json

It results with error 400 and error message:

```json
{
"response": "Invalid Query: the query is either empty or does not conform to the correct pattern. See the API documentations for additional information.",
"status_code": 400,
"status": "Bad request"
}
```

**Expected behaviour**
Correct formatted query provided with expected available data returned.

**Comment by xenatisch** [comment]
@DaveJephson / @jamesbwestwood  FYI.

**Comment by grobaan** [comment]
This issue is now resolved, thank you for bringing this to our attention @jayaddison
